### ISSUE TITLE
SLURM out file

### ISSUE THREAD

**Issue by fnattino** [EcoExtreML/Emulator#12]
Files containing the standard output from the SLURM jobs, seems to contain only Jupyter logs and job wrap ups - maybe they can be discarded for cleanness? The best way to ignore them from git, is to add `slurm-*.out` as a new line to the `.gitignore` file.

**Comment by QianqianHan96** [comment]
That is a good idea. I have add slurm-*.out as a new line to the .gitignore file. 
But I have one question, the files like slurm-3909303.out which is already uploaded to github, the updated .gitignore file does not work for it, right? Because after I updated .gitignore file, slurm-3909303.out is still in my github repository.

**Comment by fnattino** [comment]
Exactly, files that are already in the repository will remain - the change will only ignore slurm files from now on. I have removed the files and open a pull request to include changes in the repository
